### PR TITLE
adding .css to the gitignore file

### PR DESCRIPTION
**Pull request by rgovert**
because .css files are generated from .less files.

Hopefully this fixes the issue, I'll have to see if anything else doesn't work...

### CODE REVIEW

**Comment by rgovert** [comment]
I also don't know if we need to delete the css files from github... because when I discard the changes in github desktop, the site's styling goes back to being messed up

**Review by jrasch — COMMENTED** [review]
It appears there are some CSS files are supposed to be there so we can't ignore all of them; I have a script that will determine the exact ones we need and then fix the `.gitignore` file.

**Comment by rgovert** [comment]
So when I create a new .less file, will I need to add the .css file that gets generated to the gitignore file?

**Comment by jrasch** [comment]
If you pull the change I just added, the styling should work properly. You will need to download the web server one more time, as the previous package did not include the LESS compiler.

**Comment by jrasch** [comment]
Yes, you would have to make sure to ignore the CSS file. If you do not ignore one that has an associated LESS file, the build plan will issue an error and log which CSS file(s) needs to be deleted from the repository and ignored.

**Pull request merged**
